// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFMfCWPhG4wB6YLMIsWSMr0j0XihoT_9A',
    appId: '1:84286133948:web:ca36555d09c0aecc1922b9',
    messagingSenderId: '84286133948',
    projectId: 'firesafetyapp-15b56',
    authDomain: 'firesafetyapp-15b56.firebaseapp.com',
    storageBucket: 'firesafetyapp-15b56.firebasestorage.app',
    measurementId: 'G-6G6K85J5RY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAineFlNVLOcBYMRGWdV1t0rPW8fxXC9hg',
    appId: '1:84286133948:android:f16a9dec1d4c1ca51922b9',
    messagingSenderId: '84286133948',
    projectId: 'firesafetyapp-15b56',
    storageBucket: 'firesafetyapp-15b56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkMd-x4wXuRICAvTHgNLSre6zT6sX7R2Y',
    appId: '1:84286133948:ios:7bb0e931cdf5eb571922b9',
    messagingSenderId: '84286133948',
    projectId: 'firesafetyapp-15b56',
    storageBucket: 'firesafetyapp-15b56.firebasestorage.app',
    iosBundleId: 'com.example.firesafetappFixedNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkMd-x4wXuRICAvTHgNLSre6zT6sX7R2Y',
    appId: '1:84286133948:ios:7bb0e931cdf5eb571922b9',
    messagingSenderId: '84286133948',
    projectId: 'firesafetyapp-15b56',
    storageBucket: 'firesafetyapp-15b56.firebasestorage.app',
    iosBundleId: 'com.example.firesafetappFixedNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFMfCWPhG4wB6YLMIsWSMr0j0XihoT_9A',
    appId: '1:84286133948:web:e6bc31c8291372931922b9',
    messagingSenderId: '84286133948',
    projectId: 'firesafetyapp-15b56',
    authDomain: 'firesafetyapp-15b56.firebaseapp.com',
    storageBucket: 'firesafetyapp-15b56.firebasestorage.app',
    measurementId: 'G-B4ZTS2D7YS',
  );
}
